services:
  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: gps_postgres
    environment:
      POSTGRES_USER: gps_user
      POSTGRES_PASSWORD: gps_password
      POSTGRES_DB: gps_db
    ports:
      - "5432:5432"
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gps_user -d gps_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: gps_api
    environment:
      DB_HOST: postgres
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
  web_app:
    build:
      context: ./gps-web-app
      dockerfile: Dockerfile
    container_name: gps_web_app
    environment:
      API_URL: http://localhost:8080
      NEXT_PUBLIC_API_URL: http://localhost:8080
      URL: http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped
